version: '3.9'
services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: db1
      MYSQL_USER: usu
      MYSQL_PASSWORD: passtest
      MYSQL_ROOT_PASSWORD: passtestroot